apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base directory as a single resource
resources:
  - ../base

# Apply common labels or environment-specific overrides, if needed
commonLabels:
  app.kubernetes.io/version: main
  app.kubernetes.io/component: driver
  app.kubernetes.io/name: scality-cosi-driver
  app.kubernetes.io/part-of: container-object-storage-interface
  app.kubernetes.io/managed-by: kustomize
