apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectstorage-provisioner
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-scality
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-scality
spec:
  replicas: 1
  minReadySeconds: 30
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/part-of: container-object-storage-interface
      app.kubernetes.io/component: driver-scality
      app.kubernetes.io/version: main
      app.kubernetes.io/name: cosi-driver-scality
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: container-object-storage-interface
        app.kubernetes.io/component: driver-scality
        app.kubernetes.io/version: main
        app.kubernetes.io/name: cosi-driver-scality
    spec:
      serviceAccountName: objectstorage-provisioner-sa
      volumes:
      - name: socket
        emptyDir: {}
      containers:
      - name: scality-cosi-driver
        image: $(SCALITY_IMAGE_ORG)/scality-cosi-driver:$(SCALITY_IMAGE_VERSION)
        imagePullPolicy: IfNotPresent
        args:
          - "--driver-prefix=cosi"
          - "--v=5"  # Verbose mode
        volumeMounts:
        - mountPath: /var/lib/cosi
          name: socket
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      - name: objectstorage-provisioner-sidecar
        image: gcr.io/k8s-staging-sig-storage/objectstorage-sidecar:latest
        imagePullPolicy: IfNotPresent
        args:
        - "--v=5"  # Verbose mode
        volumeMounts:
        - mountPath: /var/lib/cosi
          name: socket
