---
apiVersion: v1
kind: Namespace
metadata:
  name: scality-cosi-driver
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-scality
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-scality
