name: CI

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      # Install Ginkgo CLI
      - name: Install Ginkgo CLI
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: make test

  windows-container-build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build windows image
        run: >
          docker build
          --tag ghcr.io/${{ github.repository }}:${{ github.sha }}
          --platform=windows/amd64
          --build-arg TARGETOS=windows
          .
      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
  dev-container-build:
    uses: scality/workflows/.github/workflows/docker-build.yaml@feature/PTFE-2104-support-platforms
    strategy:
      matrix:
        platforms:
          - linux/amd64
          - linux/arm64
    with:
      context: .
      name: cosi
      namespace: ${{ github.repository_owner }}
      tag: ${{ github.sha }}
      platforms: ${{ matrix.platforms }}
