name: KIND Kubernetes CI

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create k8s KIND Cluster
        uses: helm/kind-action@v1.10.0
        with:
          version: v0.21.0
          wait: 90s
          cluster_name: object-storage-cluster

      - name: Verify KIND cluster is running
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true

      # Step 4: Install CRDs and COSI Controller
      - name: Install COSI CRDs
        run: |
          kubectl create -k github.com/kubernetes-sigs/container-object-storage-interface-api
          kubectl create -k github.com/kubernetes-sigs/container-object-storage-interface-controller

      # Step 5: Verify COSI Controller Pod Status
      - name: Verify COSI Controller Pod is running
        run: |
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=container-object-storage-interface-controller -n default --timeout=120s
          kubectl get pods -n default | grep objectstorage-controller

      - name: Build cosi driver image
        run: |
          docker build -t github.com/scality/cosi:latest .

      - name: Load cosi driver image into KIND cluster
        run: |
          kind load docker-image github.com/scality/cosi:latest --name object-storage-cluster
